server:
  port: 9000
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
    enabled: true
    ciphers: ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA
    protocol: TLS
    key-alias: mydomain